[package]
name = "fiv-log"
version = "0.1.0"
edition = "2021"

[net]
git-fetch-with-cli=true

[dependencies]
fiv-date={git="ssh://github.com/Fives-55555/fiv-date.git",rev = "ff6143cdff9c5387a62f2abc984e5dfb1a966f50"}